/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gmyers' at '5/2/14 12:04 PM' with Gradle 1.11
 *
 * @author gmyers, @date 5/2/14 12:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
